type DemoIncident = {
  title: string;
  service: 'Checkout API' | 'Auth Service' | 'Payments API';
  severity: 'CRITICAL' | 'HIGH' | 'LOW';
  daysAgo: number;
  alerts: number;
  minutesToAcknowledge: number | null;
  minutesToResolve: number | null;
};

export const DEMO_INCIDENTS: DemoIncident[] = [
  {
    title: 'Database connection pool exhausted',
    service: 'Checkout API',
    severity: 'CRITICAL',
    daysAgo: 29,
    alerts: 6,
    minutesToAcknowledge: 3,
    minutesToResolve: 42,
  },
  {
    title: 'Elevated 5xx rate on /api/orders',
    service: 'Checkout API',
    severity: 'HIGH',
    daysAgo: 27,
    alerts: 3,
    minutesToAcknowledge: 6,
    minutesToResolve: 31,
  },
  {
    title: 'Login latency above 2s',
    service: 'Auth Service',
    severity: 'HIGH',
    daysAgo: 26,
    alerts: 2,
    minutesToAcknowledge: 4,
    minutesToResolve: 18,
  },
  {
    title: 'Payment webhook timeout',
    service: 'Payments API',
    severity: 'HIGH',
    daysAgo: 24,
    alerts: 4,
    minutesToAcknowledge: 9,
    minutesToResolve: 55,
  },
  {
    title: 'Disk usage above 80%',
    service: 'Checkout API',
    severity: 'LOW',
    daysAgo: 23,
    alerts: 1,
    minutesToAcknowledge: 22,
    minutesToResolve: 95,
  },
  {
    title: 'Token refresh failures',
    service: 'Auth Service',
    severity: 'CRITICAL',
    daysAgo: 21,
    alerts: 8,
    minutesToAcknowledge: 2,
    minutesToResolve: 27,
  },
  {
    title: 'Card processor returning 503',
    service: 'Payments API',
    severity: 'CRITICAL',
    daysAgo: 19,
    alerts: 5,
    minutesToAcknowledge: 4,
    minutesToResolve: 64,
  },
  {
    title: 'Cart service memory climbing',
    service: 'Checkout API',
    severity: 'LOW',
    daysAgo: 18,
    alerts: 1,
    minutesToAcknowledge: 14,
    minutesToResolve: 40,
  },
  {
    title: 'Password reset emails delayed',
    service: 'Auth Service',
    severity: 'LOW',
    daysAgo: 16,
    alerts: 2,
    minutesToAcknowledge: 11,
    minutesToResolve: 36,
  },
  {
    title: 'Checkout page error rate above 5%',
    service: 'Checkout API',
    severity: 'CRITICAL',
    daysAgo: 14,
    alerts: 7,
    minutesToAcknowledge: 3,
    minutesToResolve: 22,
  },
  {
    title: 'Refund queue backlog',
    service: 'Payments API',
    severity: 'HIGH',
    daysAgo: 12,
    alerts: 3,
    minutesToAcknowledge: 7,
    minutesToResolve: 48,
  },
  {
    title: 'Session store unreachable',
    service: 'Auth Service',
    severity: 'CRITICAL',
    daysAgo: 10,
    alerts: 9,
    minutesToAcknowledge: 2,
    minutesToResolve: 16,
  },
  {
    title: 'Slow queries on orders table',
    service: 'Checkout API',
    severity: 'HIGH',
    daysAgo: 8,
    alerts: 2,
    minutesToAcknowledge: 5,
    minutesToResolve: 33,
  },
  {
    title: 'Certificate expires in 7 days',
    service: 'Payments API',
    severity: 'LOW',
    daysAgo: 6,
    alerts: 1,
    minutesToAcknowledge: 30,
    minutesToResolve: 120,
  },
  {
    title: 'Inventory sync failing',
    service: 'Checkout API',
    severity: 'HIGH',
    daysAgo: 5,
    alerts: 4,
    minutesToAcknowledge: 6,
    minutesToResolve: 29,
  },
  {
    title: 'OAuth callback errors',
    service: 'Auth Service',
    severity: 'HIGH',
    daysAgo: 3,
    alerts: 3,
    minutesToAcknowledge: 4,
    minutesToResolve: 21,
  },
  {
    title: 'Duplicate charge reports',
    service: 'Payments API',
    severity: 'CRITICAL',
    daysAgo: 2,
    alerts: 5,
    minutesToAcknowledge: 3,
    minutesToResolve: 38,
  },
  {
    title: 'Search results timing out',
    service: 'Checkout API',
    severity: 'HIGH',
    daysAgo: 1,
    alerts: 2,
    minutesToAcknowledge: 5,
    minutesToResolve: 24,
  },
  {
    title: 'Payout batch stuck',
    service: 'Payments API',
    severity: 'HIGH',
    daysAgo: 0,
    alerts: 2,
    minutesToAcknowledge: 4,
    minutesToResolve: null,
  },
  {
    title: 'Signup rate limiter rejecting real users',
    service: 'Auth Service',
    severity: 'CRITICAL',
    daysAgo: 0,
    alerts: 3,
    minutesToAcknowledge: null,
    minutesToResolve: null,
  },
];
